const state = { result: null, view: 'overview', protocolTab: 'dns', finding: null };
const $ = sel => document.querySelector(sel);
const content = $('#content');
const loading = $('#loading');
const notice = $('#notice');
const fileInput = $('#fileInput');
const jsonBtn = $('#jsonBtn');
const reportBtn = $('#reportBtn');
const pageTitle = $('#pageTitle');
const sessionState = $('#sessionState');
const closeSessionBtn = $('#closeSessionBtn');
const modal = $('#findingModal');
const modalBody = $('#modalBody');
const modalTitle = $('#modalTitle');

const fmtNum = n => Number(n || 0).toLocaleString();
const fmtBytes = n => { let v=Number(n||0), u=['B','KB','MB','GB','TB'],i=0; while(v>=1024&&i<u.length-1){v/=1024;i++} return `${i?v.toFixed(1):Math.round(v)} ${u[i]}` };
const fmtTime = ts => Number(ts) ? new Date(Number(ts)*1000).toISOString().replace('T',' ').replace('Z',' UTC') : '—';
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const endpoint = e => `${esc(e.src || '—')}${e.sport != null ? ':'+esc(e.sport):''} → ${esc(e.dst || '—')}${e.dport != null ? ':'+esc(e.dport):''}`;
const shortHash = value => value ? `${value.slice(0,12)}…${value.slice(-8)}` : '—';

function setBusy(on){ loading.classList.toggle('hidden', !on); fileInput.disabled=on; }
function setResult(result){ state.result=result; state.view='overview'; state.protocolTab='dns'; jsonBtn.disabled=false; reportBtn.disabled=false; notice.classList.add('hidden'); updateSessionState(); selectNav(); render(); }
function showError(message){ content.innerHTML=`<div class="warning"><strong>Analysis failed.</strong> ${esc(message)}</div>`; }
function updateSessionState(){ const r=state.result; if(!r){sessionState.textContent='No active investigation';closeSessionBtn.classList.add('hidden');return} sessionState.textContent=r.session_id?`Session ${r.session_id.slice(0,8)} · evidence ${r.capture?.evidence_id||'—'}`:`Evidence ${r.capture?.evidence_id||'—'}`; closeSessionBtn.classList.toggle('hidden',!r.session_id); }
function selectNav(){ document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view)); }

async function analyzeFile(file){
  setBusy(true);
  try{
    const res=await fetch(`/api/analyze?filename=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});
    const data=await res.json(); if(!res.ok) throw new Error(data.detail||'Unable to analyze capture'); setResult(data);
  }catch(err){showError(err.message)} finally{setBusy(false);fileInput.value=''}
}
async function loadDemo(){ setBusy(true); try{const res=await fetch('/api/demo');const data=await res.json();if(!res.ok)throw new Error(data.detail||'Demo unavailable');setResult(data)}catch(err){showError(err.message)}finally{setBusy(false)} }
async function refreshSession(){ if(!state.result?.session_id)return; const res=await fetch(`/api/sessions/${state.result.session_id}`); if(res.ok){state.result=await res.json();render();} }
async function closeSession(){ if(!state.result?.session_id)return; await fetch(`/api/sessions/${state.result.session_id}`,{method:'DELETE'}); state.result=null; location.reload(); }

fileInput.addEventListener('change',e=>e.target.files?.[0]&&analyzeFile(e.target.files[0]));
$('#demoBtn').addEventListener('click',loadDemo); $('#demoBtn2').addEventListener('click',loadDemo); closeSessionBtn.addEventListener('click',closeSession);
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;selectNav();render()});
jsonBtn.addEventListener('click',()=>downloadBlob(JSON.stringify(state.result,null,2),'application/json',`${captureName()}.packetscope.json`));
reportBtn.addEventListener('click',async()=>{ let res; if(state.result?.session_id)res=await fetch(`/api/sessions/${state.result.session_id}/report`);else res=await fetch('/api/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state.result)}); if(res.ok)downloadBlob(await res.text(),'text/html',`${captureName()}.report.html`); });
$('#modalClose').addEventListener('click',closeFinding); modal.addEventListener('click',e=>{if(e.target===modal)closeFinding()}); document.addEventListener('keydown',e=>{if(e.key==='Escape')closeFinding()});
function captureName(){return (state.result?.source_name||state.result?.capture?.name||'capture').replace(/\.(pcapng|pcap|cap)$/i,'')}
function downloadBlob(body,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),750)}

function render(){
  if(!state.result)return;
  const titles={overview:'Investigation overview',findings:'Analyst findings',hosts:'Host profiles',graph:'Network graph',flows:'Flow inventory',protocols:'Protocol intelligence',iocs:'IOC inventory',timeline:'Evidence timeline'};
  pageTitle.textContent=titles[state.view];
  const warnings=(state.result.warnings||[]).map(w=>`<div class="warning">${esc(w)}</div>`).join('');
  const views={overview:renderOverview,findings:renderFindings,hosts:renderHosts,graph:renderGraph,flows:renderFlows,protocols:renderProtocols,iocs:renderIOCs,timeline:renderTimeline};
  content.innerHTML=warnings+views[state.view](); bindDynamic();
}
function metric(label,value,sub,extra=''){return `<div class="card metric-card"><div class="metric-label">${esc(label)}</div><div class="metric-value">${esc(value)}</div><div class="metric-sub">${esc(sub)}</div>${extra}</div>`}
function metrics(){const r=state.result,c=r.capture,p=r.posture;return `<div class="grid metrics">
${metric('Risk score',`${p.risk_score}/100`,`${p.high} high · ${p.medium} medium`,`<div class="risk-line"><i style="width:${p.risk_score}%"></i></div>`)}
${metric('Packets',fmtNum(c.packets),`${c.parse_coverage_percent}% parse coverage`)}
${metric('Hosts',fmtNum(r.hosts.length),`${r.conversations.length} conversations`)}
${metric('Findings',fmtNum(p.findings),`${p.suppressed_findings||0} suppressed`)}
${metric('Evidence',c.evidence_id||'—',shortHash(c.sha256))}</div>`}
function findingSeverity(f){return `<span class="severity ${esc(f.severity)}">${esc(f.severity.toUpperCase())}</span>`}
function findingsTable(items){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Severity</th><th>Finding</th><th>Confidence</th><th>Category</th><th>ATT&CK</th><th>Analyst</th></tr></thead><tbody>${items.map(f=>{const a=f.analyst||{};return `<tr class="clickable finding-row" data-finding="${esc(f.id)}"><td>${findingSeverity(f)}</td><td><div class="finding-title">${esc(f.title)}</div><div class="finding-summary">${esc(f.summary)}</div><div class="rule-id">${esc(f.rule_id)}</div></td><td>${esc(f.confidence)}%</td><td>${esc(f.category)}</td><td>${esc((f.mitre||[]).map(x=>x.id).join(', ')||'—')}</td><td><span class="state-pill">${esc(a.status||'new')}</span><br><small>${esc(a.verdict||'unknown')}</small></td></tr>`}).join('')||'<tr><td colspan="6">No active heuristic findings.</td></tr>'}</tbody></table></div>`}

function renderOverview(){const r=state.result,apps=Object.entries(r.protocols.application),max=Math.max(1,...apps.map(x=>x[1]));return `${metrics()}
<div class="grid overview-grid">
<div class="card panel"><div class="panel-head"><div><h3>Protocol composition</h3><small>Application-layer classification</small></div><span class="count-chip">${fmtNum(r.capture.packets)} packets</span></div><div class="protocol-bars">${apps.slice(0,10).map(([k,v])=>`<div class="protocol-row"><span>${esc(k)}</span><div class="bar"><i style="width:${(v/max)*100}%"></i></div><strong>${fmtNum(v)}</strong></div>`).join('')||'<small>No parsed traffic</small>'}</div></div>
<div class="card panel"><div class="panel-head"><div><h3>Priority hosts</h3><small>Risk-ranked endpoints</small></div></div><table class="mini-table"><thead><tr><th>Host</th><th>Scope</th><th>Risk</th><th>Traffic</th></tr></thead><tbody>${r.hosts.slice(0,7).map(x=>`<tr><td class="mono">${esc(x.ip)}</td><td><span class="scope-tag">${esc(x.scope)}</span></td><td>${x.risk_score}/100</td><td>${fmtBytes(x.bytes_in+x.bytes_out)}</td></tr>`).join('')}</tbody></table></div></div>
<div class="evidence-strip"><div><span>SHA-256</span><code title="${esc(r.capture.sha256)}">${esc(shortHash(r.capture.sha256))}</code></div><div><span>Capture window</span><strong>${esc(r.capture.start_time||'—')} → ${esc(r.capture.end_time||'—')}</strong></div><div><span>Fragments</span><strong>${fmtNum(r.capture.fragmented_packets||0)}</strong></div></div>
<div class="section-head"><div><h2>Priority findings</h2><p>Select a lead to inspect evidence, recommendation and analyst state.</p></div><span class="count-chip">${r.findings.length} active</span></div>${findingsTable(r.findings.slice(0,7))}
<div class="section-head"><div><h2>Periodic communication</h2><p>Low-jitter recurring destination contact patterns.</p></div><span class="count-chip">${r.beacons.length} candidates</span></div><div class="card panel"><div class="beacon-list">${r.beacons.slice(0,6).map(b=>`<div class="beacon"><div><strong>${esc(b.src)} → ${esc(b.dst)}:${esc(b.dport)}</strong><small>${b.count} observations · ${b.mean_interval}s mean · CV ${b.jitter_cv}</small></div><div class="confidence">${b.confidence}%</div></div>`).join('')||'<small class="muted">No strongly periodic flows detected.</small>'}</div></div>`}
function renderFindings(){const r=state.result;return `${metrics()}<div class="section-head"><div><h2>Detection leads</h2><p>Evidence-backed heuristics with analyst workflow and packet slicing.</p></div><span class="count-chip">${r.findings.length}</span></div>${findingsTable(r.findings)}${r.suppressed_findings?.length?`<details class="suppressed"><summary>${r.suppressed_findings.length} suppressed finding(s)</summary>${findingsTable(r.suppressed_findings)}</details>`:''}`}
function renderHosts(){const rows=state.result.hosts;return `${metrics()}<div class="section-head"><div><h2>Host-centric investigation</h2><p>Traffic, protocol context, destinations and attributed findings.</p></div><span class="count-chip">${rows.length} hosts</span></div><div class="toolbar"><input class="search" id="hostSearch" placeholder="Filter IP, scope, protocol, service…"></div><div class="host-grid" id="hostGrid">${rows.map(h=>`<article class="card host-card" data-search="${esc(`${h.ip} ${h.scope} ${Object.keys(h.protocols).join(' ')} ${(h.services||[]).join(' ')}`.toLowerCase())}"><div class="host-head"><div><code>${esc(h.ip)}</code><span class="scope-tag">${esc(h.scope)}</span></div><strong class="risk-score">${h.risk_score}</strong></div><div class="host-stats"><span><b>${fmtNum(h.packets_out)}</b> out</span><span><b>${fmtNum(h.packets_in)}</b> in</span><span><b>${fmtBytes(h.bytes_out)}</b> sent</span><span><b>${h.unique_destinations}</b> destinations</span></div><div class="chip-row">${Object.entries(h.protocols).slice(0,6).map(([p,n])=>`<span>${esc(p)} · ${fmtNum(n)}</span>`).join('')}</div><div class="host-context"><small>Services</small><div>${esc((h.services||[]).join(', ')||'—')}</div><small>Domains / SNI</small><div>${esc([...(h.domains||[]),...(h.tls_sni||[])].slice(0,5).join(', ')||'—')}</div><small>Findings</small><div>${esc((h.finding_ids||[]).slice(0,5).join(', ')||'—')}</div></div></article>`).join('')}</div>`}
function renderGraph(){const g=state.result.graph||{nodes:[],edges:[]};return `<div class="section-head"><div><h2>Investigation graph</h2><p>Traffic edges plus DNS and TLS-SNI pivots. Metadata graph only; no external enrichment.</p></div><span class="count-chip">${g.nodes.length} nodes · ${g.edges.length} edges</span></div><div class="card graph-panel">${graphSvg(g)}</div><div class="legend"><span><i class="lg host"></i>Host</span><span><i class="lg domain"></i>Domain</span><span><i class="lg traffic"></i>Traffic edge</span></div>`}
function graphSvg(g){if(!g.nodes?.length)return '<div class="graph-empty">No graphable hosts.</div>';const nodes=g.nodes.slice(0,80),ids=new Set(nodes.map(n=>n.id)),edges=(g.edges||[]).filter(e=>ids.has(e.source)&&ids.has(e.target)).slice(0,180);const w=1100,h=620,cx=w/2,cy=h/2;const pos={};const hostNodes=nodes.filter(n=>n.type==='host'),domainNodes=nodes.filter(n=>n.type==='domain');hostNodes.forEach((n,i)=>{const a=(i/Math.max(1,hostNodes.length))*Math.PI*2;const radius=Math.min(225,150+hostNodes.length*2);pos[n.id]=[cx+Math.cos(a)*radius,cy+Math.sin(a)*radius]});domainNodes.forEach((n,i)=>{const a=(i/Math.max(1,domainNodes.length))*Math.PI*2+.13;const radius=285;pos[n.id]=[cx+Math.cos(a)*radius,cy+Math.sin(a)*radius]});const lines=edges.map(e=>{const a=pos[e.source],b=pos[e.target];if(!a||!b)return'';return `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" class="edge ${esc(e.type)}"><title>${esc(e.type)} · ${fmtNum(e.packets)} packets · ${fmtBytes(e.bytes)}</title></line>`}).join('');const circles=nodes.map(n=>{const p=pos[n.id];const risk=n.risk_score||0;return `<g class="graph-node ${esc(n.type)}"><circle cx="${p[0]}" cy="${p[1]}" r="${n.type==='host'?Math.min(12,7+risk/25):5}"><title>${esc(n.label)}${n.type==='host'?` · risk ${risk}/100`:''}</title></circle><text x="${p[0]+9}" y="${p[1]-9}">${esc(n.label.length>24?n.label.slice(0,22)+'…':n.label)}</text></g>`}).join('');return `<svg class="network-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="PacketScope network graph">${lines}${circles}</svg>`}
function renderFlows(){const rows=state.result.flows,convs=state.result.conversations||[],streams=state.result.streams||[];return `${metrics()}<div class="section-head"><div><h2>Bidirectional conversations</h2><p>Endpoint pairs with aggregated applications and packet evidence.</p></div><span class="count-chip">${convs.length}</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Endpoint A</th><th>Endpoint B</th><th>Transport</th><th>Applications</th><th>Packets</th><th>Bytes</th><th>Duration</th></tr></thead><tbody>${convs.slice(0,500).map(c=>`<tr><td class="mono">${esc(c.endpoint_a)}${c.port_a!=null?':'+c.port_a:''}</td><td class="mono">${esc(c.endpoint_b)}${c.port_b!=null?':'+c.port_b:''}</td><td>${esc(c.transport)}</td><td>${esc((c.applications||[]).join(', '))}</td><td>${fmtNum(c.packets)}</td><td>${fmtBytes(c.bytes)}</td><td>${Number(c.duration).toFixed(3)}s</td></tr>`).join('')}</tbody></table></div><div class="section-head"><div><h2>Directional flows</h2><p>Filter by endpoint, application or transport.</p></div><span class="count-chip">${rows.length}</span></div><div class="toolbar"><input class="search" id="flowSearch" placeholder="Filter source, destination, protocol…"></div><div class="table-wrap"><table class="data-table" id="flowTable"><thead><tr><th>Source</th><th>Destination</th><th>Transport</th><th>Application</th><th>Packets</th><th>Bytes</th><th>Payload</th><th>Duration</th></tr></thead><tbody>${rows.map(f=>`<tr data-search="${esc(`${f.src} ${f.dst} ${f.transport} ${f.application}`.toLowerCase())}"><td class="mono">${esc(f.src)}${f.sport!=null?':'+f.sport:''}</td><td class="mono">${esc(f.dst)}${f.dport!=null?':'+f.dport:''}</td><td>${esc(f.transport)}</td><td>${esc(f.application)}</td><td>${fmtNum(f.packets)}</td><td>${fmtBytes(f.bytes)}</td><td>${fmtBytes(f.payload_bytes)}</td><td>${Number(f.duration).toFixed(3)}s</td></tr>`).join('')}</tbody></table></div><div class="section-head"><div><h2>Bounded TCP reconstruction</h2><p>Sequence-aware first-contiguous-fragment reconstruction; gaps are never fabricated.</p></div><span class="count-chip">${streams.length}</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Stream</th><th>Application</th><th>Segments</th><th>Reassembled</th><th>Gaps</th><th>Overlap</th><th>Context</th></tr></thead><tbody>${streams.map(x=>`<tr><td class="mono">${esc(x.src)}:${esc(x.sport)} → ${esc(x.dst)}:${esc(x.dport)}</td><td>${esc(x.application)}</td><td>${fmtNum(x.segments)}</td><td>${fmtBytes(x.reassembled_bytes)}</td><td>${fmtNum(x.gaps)}</td><td>${fmtBytes(x.overlap_bytes)}</td><td class="mono">${esc(x.http?.host||x.tls?.sni||x.tls?.ja3_hash||x.tls?.kind||'—')}</td></tr>`).join('')||'<tr><td colspan="7">No application payload available.</td></tr>'}</tbody></table></div>`}
function renderProtocols(){const r=state.result,tabs=[['dns',r.dns_transactions?.length||0],['http',r.http_transactions?.length||r.http.length],['tls',r.tls_sessions?.length||r.tls.length],['arp',r.arp.length],['dhcp',r.dhcp.length],['icmp',r.icmp.length],['ntp',r.ntp.length]];return `<div class="section-head"><div><h2>Protocol intelligence</h2><p>Transactions and bounded metadata extracted locally.</p></div></div><div class="protocol-tabs">${tabs.map(([t,n])=>`<button data-ptab="${t}" class="${state.protocolTab===t?'active':''}">${t.toUpperCase()} · ${n}</button>`).join('')}</div>${protocolTable()}`}
function protocolTable(){const r=state.result,t=state.protocolTab;
 if(t==='dns'){const rows=r.dns_transactions||[];return table(['Client','Server','Query','QType','RCode','Answers','Latency','Packets'],rows.map(x=>[x.client,x.server,x.query,x.qtype,x.rcode,x.answers?.map(a=>typeof a.value==='object'?JSON.stringify(a.value):a.value).filter(Boolean).join(', ')||'—',x.latency_ms!=null?`${x.latency_ms} ms`:'unmatched',[x.query_packet_id,x.response_packet_id].filter(Boolean).join(', ')]));}
 if(t==='http'){const rows=r.http_transactions?.length?r.http_transactions:r.http;return table(['Client','Server','Request','Status','Host','Latency','Packets'],rows.map(x=>x.http?[x.src,x.dst,`${x.http.method||x.http.kind} ${x.http.uri||''}`,x.http.status||'—',x.http.host||'—','—',x.packet_id]:[x.client,x.server,`${x.method||'—'} ${x.uri||''}`,x.status??'—',x.host||'—',x.latency_ms!=null?`${x.latency_ms} ms`:'unmatched',[x.request_packet_id,x.response_packet_id].filter(Boolean).join(', ')]));}
 if(t==='tls'){const rows=r.tls_sessions||[];return table(['Client','Server','SNI','JA3','Selected version','Cipher','Certificate','Packets'],rows.map(x=>[`${x.client}:${x.client_port}`,`${x.server}:${x.server_port}`,x.sni||'—',x.ja3_hash||'—',x.selected_version||'—',x.cipher||'—',x.certificate?.certificates?.[0]?.subject||'—',(x.packet_ids||[]).join(', ')]));}
 if(t==='arp')return table(['Packet','Operation','Sender IP','Sender MAC','Target IP','Target MAC'],r.arp.map(x=>[x.packet_id,x.operation_name,x.sender_ip,x.sender_mac,x.target_ip,x.target_mac]));
 if(t==='dhcp')return table(['Packet','Message','Source','Offered IP','Server ID','Client MAC'],r.dhcp.map(x=>[x.packet_id,x.message_name,x.src,x.your_ip,x.server_identifier,x.client_mac]));
 if(t==='icmp')return table(['Packet','Time','Source','Destination','Type','Code','Sequence'],r.icmp.map(x=>[x.packet_id,fmtTime(x.timestamp),x.src,x.dst,x.name,x.code,x.sequence??'—']));
 return table(['Packet','Time','Source','Destination','Version','Mode','Stratum'],r.ntp.map(x=>[x.packet_id,fmtTime(x.timestamp),x.src,x.dst,x.version,x.mode,x.stratum]));
}
function table(headers,rows){return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td class="${String(v).includes('.')||String(v).includes(':')?'mono':''}">${esc(v??'—')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}">No matching protocol records.</td></tr>`}</tbody></table></div>`}
function renderIOCs(){const i=state.result.iocs;const card=(title,items)=>`<div class="card panel"><div class="panel-head"><div><h3>${esc(title)}</h3><small>${items.length} unique values</small></div></div><ul class="ioc-list">${items.slice(0,500).map(x=>`<li><span class="mono">${esc(x.value)}</span><span class="scope-tag">${esc(x.scope||x.type)}</span></li>`).join('')||'<li><span>None observed</span></li>'}</ul></div>`;return `<div class="section-head"><div><h2>Extracted observables</h2><p>Local inventory only; no reputation lookup is performed automatically.</p></div></div><div class="grid ioc-grid">${card('Domains',i.domains)}${card('IP addresses',i.ips)}${card('URLs',i.urls)}${card('JA3 fingerprints',i.ja3)}${card('Certificate SHA-256',i.certificate_sha256||[])}</div>`}
function renderTimeline(){const rows=state.result.timeline.slice(0,1500);return `<div class="section-head"><div><h2>Packet evidence timeline</h2><p>Representative parsed packet events in chronological order.</p></div><span class="count-chip">${rows.length} displayed</span></div><div class="card panel"><div class="timeline">${rows.map(e=>`<div class="timeline-item"><div class="timeline-time">#${esc(e.packet_id)} · ${fmtTime(e.timestamp)}</div><div class="timeline-main"><strong>${esc(e.application)}</strong> · ${endpoint(e)}</div><div class="timeline-meta">${e.payload_bytes?fmtBytes(e.payload_bytes)+' application payload · ':''}${fmtBytes(e.length)} frame · DLT ${esc(e.linktype)}</div></div>`).join('')||'<small>No parsed events.</small>'}</div></div>`}

function bindDynamic(){
 document.querySelectorAll('[data-ptab]').forEach(b=>b.addEventListener('click',()=>{state.protocolTab=b.dataset.ptab;render()}));
 document.querySelectorAll('[data-finding]').forEach(row=>row.addEventListener('click',()=>openFinding(row.dataset.finding)));
 const flow=$('#flowSearch');if(flow)flow.addEventListener('input',()=>filterRows('#flowTable tbody tr',flow.value));
 const host=$('#hostSearch');if(host)host.addEventListener('input',()=>{const n=host.value.toLowerCase();document.querySelectorAll('#hostGrid [data-search]').forEach(x=>x.style.display=x.dataset.search.includes(n)?'':'none')});
}
function filterRows(sel,value){const n=value.toLowerCase();document.querySelectorAll(sel).forEach(x=>x.style.display=(x.dataset.search||'').includes(n)?'':'none')}
function openFinding(id){const f=state.result.findings.find(x=>x.id===id)||state.result.suppressed_findings?.find(x=>x.id===id);if(!f)return;state.finding=f;modalTitle.textContent=f.title;const a=f.analyst||{status:'new',verdict:'unknown',note:'',tags:[]};const packetIds=f.evidence?.packet_ids||[];modalBody.innerHTML=`<div class="modal-grid"><section><div class="finding-meta">${findingSeverity(f)}<span>${esc(f.confidence)}% confidence</span><code>${esc(f.rule_id)}</code></div><p>${esc(f.summary)}</p><h3>Recommendation</h3><p>${esc(f.recommendation||'Validate this finding in environmental context.')}</p><h3>ATT&CK context</h3><div class="chip-row">${(f.mitre||[]).map(x=>`<span>${esc(x.id)} · ${esc(x.name)}</span>`).join('')||'<span>No direct mapping</span>'}</div><h3>Evidence</h3><pre>${esc(JSON.stringify(f.evidence||{},null,2))}</pre>${packetIds.length&&state.result.session_id?`<a class="button ghost" href="/api/sessions/${state.result.session_id}/findings/${encodeURIComponent(f.id)}/slice">Export ${packetIds.length} related packet${packetIds.length===1?'':'s'} (.pcapng)</a>`:''}</section><aside><h3>Analyst workflow</h3>${state.result.session_id?`<label>Status<select id="findingStatus">${['new','triage','investigating','contained','resolved','dismissed'].map(x=>`<option ${a.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Verdict<select id="findingVerdict">${['unknown','benign','suspicious','malicious','false_positive'].map(x=>`<option ${a.verdict===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Tags<input id="findingTags" value="${esc((a.tags||[]).join(', '))}" placeholder="c2, workstation, investigate"></label><label>Analyst note<textarea id="findingNote" rows="8" placeholder="Record validation steps, ownership or disposition…">${esc(a.note||'')}</textarea></label><button class="button primary" id="saveFinding">Save analyst state</button><div class="save-state" id="saveState"></div>`:'<p class="muted">Analyst state is available for web-upload sessions.</p>'}</aside></div>`;modal.classList.remove('hidden');if(state.result.session_id)$('#saveFinding').addEventListener('click',saveFinding)}
function closeFinding(){modal.classList.add('hidden');state.finding=null}
async function saveFinding(){const f=state.finding;if(!f||!state.result.session_id)return;const payload={status:$('#findingStatus').value,verdict:$('#findingVerdict').value,note:$('#findingNote').value,tags:$('#findingTags').value.split(',').map(x=>x.trim()).filter(Boolean)};const s=$('#saveState');s.textContent='Saving…';const res=await fetch(`/api/sessions/${state.result.session_id}/findings/${encodeURIComponent(f.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok){s.textContent=data.detail||'Save failed';return}f.analyst=data;s.textContent='Saved';await refreshSession();setTimeout(()=>{if(s)s.textContent=''},1200)}
